### PR TITLE
Load content scripts in iframes and pages loaded via file protocol

### PR DESCRIPTION
**Pull request by mathewjoe**

### CODE REVIEW

**Comment by sachinsudheendra** [comment]
Hey @disrupticons, how are you doing? Long time. Thanks for the PR. :)

I tried your changes but I wasn't able to fill when the page was loaded using `file://`. Also, the iframe in `test/page.html` wasn't populating. Am I missing something?

**Comment by mathewjoe** [comment]
@sachinsudheendra Hey, I'm doing fine :) Long time indeed!

**Comment by mathewjoe** [comment]
I just tested on `test/page.html` and it seems to be working for me. Did you try the keyboard shortcut, button & context menu option? Is it not populating in all 3 cases?

**Comment by mathewjoe** [comment]
@sachinsudheendra Any update on this? :) Let me know if there's anything I can do to help move this along.

**Comment by sachinsudheendra** [comment]
Hey @disrupticons .. sorry for the delayed response to this. I have moved the project to ES6 and I've merged it as part of PR #4 . As part of the same PR I've incorporated your changes. I'll be closing this PR as a result. Will be publishing to chrome store in a while. Thanks for the PR 👍

**Pull request closed without merging**
