### PR TITLE
remove sourcemaps from libs

### PR DESCRIPTION
**Pull request by ArroWsGM**

### CODE REVIEW

**Review by sachinsudheendra — APPROVED** [review]

**Comment by sachinsudheendra** [comment]
Thank you for the PR @ArroWsGM 👍

**Comment by sachinsudheendra** [comment]
v1.15 has been published to Chrome Web Store. It'll take a few hours to autoupdate to latest version.

**Comment by ArroWsGM** [comment]
@sachinsudheendra Thanks for the great extension

**Comment by ArroWsGM** [comment]
@sachinsudheendra , unfortunately still v 1.14 in the Chrome web store

**Pull request merged**
